baseURL = "/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true

title = "Kato-k's note"
theme = "mainroad"

paginate = 20

[Author]
    name = "Kato-k"
    bio = "ただのこうこうせい"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/notosansjp.css", "css/custom.css"]
    copyright = "Kota Kato"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]

[Params.style.vars]
  highlightColor = "#44617b"

[Params.widgets.social]
  twitter = "uvrub"
  github = "kato-k"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social", "twitter"]
