baseURL = "https://kato-k.github.io/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

title = "忘れないように…"
theme = "mainroad"

paginate = 20

[Author]
    name = "Kato-k"
    bio = ""
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/notosansjp.css", "css/custom.css"]
    copyright = "Kota Kato"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true


[Params.style.vars]
  highlightColor = "#e22d30"

[Params.widgets.social]
  twitter = "uvrub"
  github = "kato-k"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social", "twitter"]

[[Menus.footer]]
  Name = "プライバシーポリシー"
  URL = "/privacy/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
