baseURL = "https://blog.kat0h.com/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

title = "kat0h's blog"
theme = "mainroad"

paginate = 20

[Author]
    name = "kat0h"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/notosansjp.css", "css/custom.css"]
    copyright = "Kota Kato"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true


[Params.style.vars]
  highlightColor = "#e22d30"

[Params.widgets.social]
  twitter = "kat0h"
  github = "kat0h"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

[[Menus.footer]]
  Name = "プライバシーポリシー"
  URL = "/privacy/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
